### ISSUE TITLE
Could you share the pretrained model?

### ISSUE THREAD

**Issue by Hans1984** [Ehzoahis/DEReD#1]
Hi, nice work, could share the pretrained model? Thanks a lot.

**Comment by Ehzoahis** [comment]
Thank you for your appreciation. We have released our model weights trained on the NYUv2 dataset [here](https://drive.google.com/file/d/1LQUt7Lo6KPKb0OsBETkvxeujOVdqOGjh/view?usp=share_link). We highly recommend you fine-tune the model on your own dataset if the settings(depth range to be specific) are different.
