### ISSUE TITLE
Hello, does the NYU dataset focal stack you generated have five images?

### ISSUE THREAD

**Issue by gaohaoxuan** [Ehzoahis/DEReD#10]
Hello, does the NYU dataset focal stack you generated have five images?
Can you tell me where to download the NYU dataset?

**Comment by firepa** [comment]
me too

**Comment by Ehzoahis** [comment]
The NYUv2 dataset is simply https://cs.nyu.edu/~fergus/datasets/nyu_depth_v2.html
The code for focal stack generation is provided in the repo.
