### ISSUE TITLE
How long does it take on average to process one scene from the DefocusNet dataset on a 4090?

### ISSUE THREAD

**Issue by gaohaoxuan** [Ehzoahis/DEReD#11]
How long does it take on average to process one scene from the DefocusNet dataset on a 4090?

**Comment by Ehzoahis** [comment]
By process, did you mean generate or inference?

**Comment by gaohaoxuan** [comment]
> By process, did you mean generate or inference?
inference

**Comment by Ehzoahis** [comment]
Evaluating 500 samples with batch size 32 takes 32 seconds on a single node A100 server. You can take that as a reference.

**Comment by gaohaoxuan** [comment]
> Evaluating 500 samples with batch size 32 takes 32 seconds on a single node A100 server. You can take that as a reference.

thanks
