### ISSUE TITLE
can't get the correct aif and dpt map with the pretrain model

### ISSUE THREAD

**Issue by hanliangwei** [Ehzoahis/DEReD#12]
Hi, thanks for your exciting paper. I want to reproduce it and finetune it.But i meet some question when i test it.
1. Process the nyuv2 dataset with https://github.com/VainF/nyuv2-python-toolkit, it get the 16bit png depth.
2.Modify the divisor from 1e4 t 1e3 in gen_nyuv2_defocus.py. Now it can generate the focus stack.
3.Add some codes in eval_model()
``` python
                print(f"\npred_dpt min{pred_dpt.min()},max{pred_dpt.max()}, shape:{pred_dpt.shape}")
                print(f"raw_aif min{raw_aif.min()},max{raw_aif.max()}, shape:{raw_aif.shape}")

                pred_aif = raw_aif.squeeze().permute(1, 2, 0).cpu().numpy()
                pred_aif = (np.clip(pred_aif, 0, 1)* 255).astype(np.uint8)
                #pred_aif = cv2.cvtColor(pred_aif, cv2.COLOR_RGB2BGR)
                cv2.imwrite(rf"D:\paper\depth_from_focus\DAIF-Net\exp\test\result\aif{i}.png",
                            pred_aif)

                dpt = pred_dpt.permute(1, 2, 0).numpy()
                save_depth(dpt,rf"D:\paper\depth_from_focus\DAIF-Net\exp\test\result\depth{i}.png")
```
Run the eval command then get the pred aif and dptimage.But the aif image seems has the color shift and the dpt is incorrect.Here is my  results. Could you give me some advice to fix the error, Thank you.
![image](https://github.com/user-attachments/assets/916df9db-b159-49f7-8ce7-718018a566c2)
I found that the max depth is in the corner
![image](https://github.com/user-attachments/assets/94af1a59-10a5-494f-8e28-ac803cb814d7)

**Comment by Ehzoahis** [comment]
Hi! I would suggest you first visualize the defocus map for defocus image generation to see if it actually makes sense. It would be nice if you could also share some sample defocus maps with me so I can double-check. Thanks!

**Comment by hanliangwei** [comment]
Thanks for your response, here is the defocus map corresponding to the focus stack of the previous comment.(save here 
 **gen_nyuv2_defocus.py** defocus = camera.getCoC(dpt, fd).type(torch.float32)  )
![image](https://github.com/user-attachments/assets/1f10b2d7-d0e5-4896-8e0c-31fcd617d82e)

**Comment by Ehzoahis** [comment]
So the defocus map looks correct. Did you evaluate the quantitative results of the depth reconstruction? Since the erroneous point seems to be the white frame of the original NYU_v2 image. Can you visualize the depth map with the white frame removed as well?

**Comment by hanliangwei** [comment]
I tried to remove the white boundary. 
``` python
img_all = cv2.imread(os.path.join(self.all_path, self.imglist_all[img_idx + i])) / 255.
 # my add ###############
img_all = img_all[16:-16,16:-16,:]
################
```
Here is the result, the most deep point still in the corner.And the aif image boundary looks strange。
![image](https://github.com/user-attachments/assets/78f56d34-6758-4814-84bf-608dfe43a239)
The quantitative results：
![image](https://github.com/user-attachments/assets/04db7775-1ecd-48e3-9174-060903982ee8)

**Comment by Ehzoahis** [comment]
Can you run all the tests and report the average performance? Also, compare it with the reported performance. If not match, it may be the problem of the dataset, otherwise, it is the issue of visualization.
