### ISSUE TITLE
Error compiling the gauss_psf_cuda.cpp

### ISSUE THREAD

**Issue by saqibnaziir** [Ehzoahis/DEReD#2]
Hi, thank you very much for the code, I am trying to compile the code but it is giving me a Compiling error:

File "/home/cristian/Documents/ToF_improvement/d3net_depth_estimation/pytorch/venv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

even after meeting the requirements. Could please tell me how did you compile it?

**Comment by Ehzoahis** [comment]
We referred the code for gasuss_psf from https://github.com/shirgur/UnsupervisedDepthFromFocus, you may find more details from their repo.
