### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'normalize_dpt'

### ISSUE THREAD

**Issue by XComedian** [Ehzoahis/DEReD#3]
Hi! When I run your scrpits to train DefocusNet data, I found that your args.py have no parameters called "normalize_dpt".

**Comment by Ehzoahis** [comment]
Hi! The "normalize_dpt" is a deprecated function, which was used to load a specific dataset. Our method can be used to predict the absolute depth. Therefore, normalizing depth as a preprocess is unnecessary as long as the defocus data is self-consistent.

**Comment by XComedian** [comment]
Got it! Thank you!
________________________________

**Comment by razgzy** [comment]
When i evaluate NYU with provided cktps, the maxinum of output raw_depth is around 1. The NYU GTs are within [0, 10]. The normalization in dpt_post_op does not make it convincible.
![image](https://github.com/Ehzoahis/DEReD/assets/61395772/1dc5bfb5-fb58-404b-9ad4-61b2c76df3d2)
left: GT, right: estimate with normalize_dpt in dpt_post_op

**Comment by Ehzoahis** [comment]
Sorry, I didn't get it, but are you using normalization? As I mentioned it is deprecated.

**Comment by razgzy** [comment]
![image](https://github.com/Ehzoahis/DEReD/assets/61395772/dd17f060-cf9c-4d8c-a0b7-1d06ef6f6fa8)
without normalization, the most of predict depth is between [0,1]

**Comment by Ehzoahis** [comment]
How did you generate your defocus NYUv2 data?

**Comment by razgzy** [comment]
using gen_nyuv2_defocus.py with default parameter and i replace 1e4 with 1e3 to rescale depth gt to [0, 10]

**Comment by razgzy** [comment]
using inpainted depth of NYU, the raw depth of NYU is worser

**Comment by Ehzoahis** [comment]
You should keep 1e-4, that is the correct parameter to normalize NYUv2 Depth.

**Comment by razgzy** [comment]
The focal stack of 1e4, depth GT [0.18, 0.36028]
![image](https://github.com/Ehzoahis/DEReD/assets/61395772/721f9625-a56d-4889-a56f-b1db05ed7631)
The focal stack of 1e3, depth GT [1.8, 3.6028]
![image](https://github.com/Ehzoahis/DEReD/assets/61395772/f6eeac34-a5f4-46d0-a20b-05c4537092aa)
using 1e4, the predict raw depth is within [0, 1] as well

**Comment by Ehzoahis** [comment]
What is the range of your depth GT without processing?

**Comment by Ehzoahis** [comment]
Your may refer to this issue: https://github.com/Ehzoahis/DEReD/issues/6

**Comment by razgzy** [comment]
[0, 10000]
in other monocular depth codes , i use divisor of 1e3
But the predict depth are both between [0, 1] using 1e3 or 1e4

**Comment by razgzy** [comment]
My predict depth has convincible shape but wrong depth range

**Comment by Ehzoahis** [comment]
Yes, that is probably because the render focal has some problem.

**Comment by razgzy** [comment]
The code i use
![image](https://github.com/Ehzoahis/DEReD/assets/61395772/e9404e17-d06c-407e-af08-67906c697a3d)
I figure that my focal stack is little different from yours in supplement

**Comment by Ehzoahis** [comment]
If your depth is a PNG, then you probably need to double-check the devisor.

**Comment by razgzy** [comment]
the depth range of my test set is around（0.7，10）. i think the depth range is right.
raw depth of nyu is (0, 10), i use inpainted depth

**Comment by Ehzoahis** [comment]
Please make sure the depth you feed into getCoC is within (0, 10) range.

**Comment by razgzy** [comment]
yes, its's within 0, 10
and my defocus stack's range is similar with yours.
you used the raw depth to generate defocus which has missing depth value filled with 0？
but i think my problem is not focus render

**Comment by Ehzoahis** [comment]
Yeah, the infinite depth is zero in my implementation. That can be the reason.

**Comment by no-Seaweed** [comment]
> to train DefocusNet data, I found that your args.py have no parameters called "normalize_dpt".

Would you mind to share how you process the NYUv2 depth? Especially, details about which version of NYUv2 you get and what processing script you use? I also have a question about the performance on NYUv2. The dataset I have is the original NYUv2(I guess?), where the depth is in range of 0~10000. By changing the setup of focal distance and setup of camera in previous issues, I  was able to obtain kinda correct depth result, but metrics are way worse than yours.
