### ISSUE TITLE
Issues about the training results on DefocusNet data

### ISSUE THREAD

**Issue by XComedian** [Ehzoahis/DEReD#4]
![image](https://github.com/Ehzoahis/DEReD/assets/142633370/eb3f5fe3-9baa-4ea1-8295-63f227c39517)
Here is the training result on DefocusNet data, I just use the dataloader and parameters you provided, but the result seems wired.

**Comment by Ehzoahis** [comment]
Did you use the DefocusNet data from the original paper?

**Comment by XComedian** [comment]
> Did you use the DefocusNet data from the original paper?

The DefocusNet data  I used has 500 focal stacks, and I download it from this url: https://drive.google.com/file/d/1bR-WZQf44s0nsScC27HiEwaXPyEQ3-Dw/view?usp=sharing

**Comment by Ehzoahis** [comment]
As we suggested in our paper, we rendered our own DefocusNet so that the defocus blur is distinguishable in the generated image. The generation code is provided by DefocusNet as well and you can generate your own dataset accordingly.

**Comment by XComedian** [comment]
> As we suggested in our paper, we rendered our own DefocusNet so that the defocus blur is distinguishable in the generated image. The generation code is provided by DefocusNet as well and you can generate your own dataset accordingly.

Yeah, I also used NYUv2 dataset and your gen_nyuv2_defocus.py to generate deofcus. I thought there will be different defocus position in the focal stack, but the results seem that the entire image is blurred.  Here is the generated defocus image
![image](https://github.com/Ehzoahis/DEReD/assets/142633370/6e9a79ef-82ae-4d40-bbab-0c656b18d114)

**Comment by Ehzoahis** [comment]
Can you visualize the generated defocus map to do a sanity check?

**Comment by XComedian** [comment]
> Can you visualize the generated defocus map to do a sanity check?
Sorry, What do you mean by doing a sanity check? During training, I can get visualization output of gt defocus map and reconstructed defocus map.

**Comment by XComedian** [comment]
> Can you visualize the generated defocus map to do a sanity check?

Sorry, What do you mean by doing a sanity check? During training, I can get visualization output of gt defocus map and reconstructed defocus map.

**Comment by Ehzoahis** [comment]
When you generate the defocus NYUv2 dataset, have you tried to visualize the defocus map?

**Comment by XComedian** [comment]
> When you generate the defocus NYUv2 dataset, have you tried to visualize the defocus map?

![image](https://github.com/Ehzoahis/DEReD/assets/142633370/6f9ccd57-0fe9-4074-927e-83d29f9fbfe0)
Here is the recon_defocus map. I also try to train your model on mobileNet data, the result is similar to feature map with 1000 epoches training. I used the default parameter settings. Could it be that I set these parameters incorrectly?

python scripts/train.py --data_path ../hard/mDFF1 --dataset mobileDFD --recon_all -N mDFF --use_cuda -E 1000 --BS 32 --save_checkpoint --save_best --save_last --sm_loss_beta 2.5 --verbose --recon_loss_lambda 1e3 --aif_blur_loss_lambda 10 --blur_loss_lambda 1e1 --sm_loss_lambda 1e1 --log --vis

**Comment by Ehzoahis** [comment]
1. For the generated defocus NYUv2 dataset, does it have a proper focal stack generated?
2.  For the recon_defocus, you may need to tune up the recon loss a little bit.

**Comment by XComedian** [comment]
> 1. For the generated defocus NYUv2 dataset, does it have a proper focal stack generated?
> 2. For the recon_defocus, you may need to tune up the recon loss a little bit.

The generated defocus NYUv2 dataset is not good yet. It seems I can't get the same focal stack as in your paper. Should I adjust the parameters in the gen_nyuv2_defocus.py?

**Comment by Ehzoahis** [comment]
You probably should. I also suggest that you move the code to a Jupyter Notebook, and visualize the intermediate defocus maps to check if that makes sense.

**Comment by XComedian** [comment]
> You probably should. I also suggest that you move the code to a Jupyter Notebook, and visualize the intermediate defocus maps to check if that makes sense.

OK, I 'll try! Appreciate for your help.
