### ISSUE TITLE
Different NYUv2 Defocus parameter setting

### ISSUE THREAD

**Issue by VuHuy-cse-9** [Ehzoahis/DEReD#5]
Hi, thanks for your great work!.
I saw that your have different Camera parameter's setting in utils/gen_nyuv2_defocus.py and utils/data_config for NYUv2 option. The first one has similar setting mentioned in paper. 
Which parameter did you use for your provided checkpoint?

**Comment by Ehzoahis** [comment]
Hi, thanks for pointing out the mismatch. You should use the one mentioned in the paper, i.e., the one in gen_nyuv2_defocus.py.
