### ISSUE TITLE
can you share your defoucs net blender script

### ISSUE THREAD

**Issue by andy4120** [Ehzoahis/DEReD#7]
hi , I am having issue with https://github.com/dvl-tum/defocus-net blender due to the version updated problem ,I modify the code ,it only blur the first color image ,the others keep changeless  ,can u share your script,Or can you tell me what place your modify the blender code,thank you very much

**Comment by Ehzoahis** [comment]
Hi. Unfortunately, I asked a previous colleague to modify the code and I have left that group. I think you may need to look into the tutorial of Blender. Sorry for cannot provide extra help.

**Comment by andy4120** [comment]
ok,thank you!
